name: frenzi_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  awesome_dialog: ^3.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  intl_utils: ^2.8.10
  google_maps_flutter: ^2.5.3
  geocoding: ^2.1.1
  google_places_flutter: ^2.1.0
  flutter_polyline_points: ^2.1.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  live_currency_rate: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/json/completed_trip_list.json
    - assets/json/journey_to_add.json

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
    lottie: true
  colors:
    inputs:
      - assets/color/colors.xml

flutter_intl:
  enabled: true
